#!/usr/bin/env bash

help(){
    echo -e "ansicolor\t\tprint all the 256 ansi color codes"
    echo -e "ansicolor -b\t\tprint all the 256 ansi color codes (background colored output)"
    echo -e "ansicolor <n>\t\t(0 <= n <= 255) print some strings in the n ansi color"
    echo -e "ansicolor -b <n>\t(0 <= n <= 255) print some strings in the n ansi color (background colored output)"
    exit 0
}

wrong_args() {
    echo  "Invalid argument for ${2}: ${1}, type ansicolor -h for usage." 1>&2
    exit -1
}

ansicolor_table() {
    local c_mode
    local c_type
    c_type="${1}"
    c_mode="${2:-0}"
    local i
    printf "\nStandard:\t"
    for i in {0..7}; do
        printf "%b%5d " "\x1b[${c_mode};${c_type};5;${i}m" "$i"
    done
    printf "\033[0;10m\n\nIntense:\t"
    for i in {8..15}; do
        printf "%b%5d " "\x1b[${c_mode};${c_type};5;${i}m" "$i"
    done
    printf "\033[0;10m\n\n\n\t\t"
    local j
    local k
    for i in {0..26}; do
        for j in {0..7}; do
            ((k = i * 8 + j + 16))
            printf "%b%5d " "\x1b[${c_mode};${c_type};5;${k}m" "$k"
        done
        printf "\033[0;10m\n\t\t"
    done
    printf "\n\nGreys:\t\t"
    for i in {232..255}; do
        printf "%b%5d " "\x1b[${c_mode};${c_type};5;${i}m" "$i"
    done
    printf "\033[0;10m\n\n"
}

ansicolor_list() {
    local c_mode
    local c_type
    local color
    c_type="${1}"
    color="${2}"
    modes=({0..10})
    c_mode="${3:-${modes[@]}}"
    local text
    local i
    for i in ${c_mode[@]}; do
        text="\\x1b[${i};${color_type};5;${color}m"
        printf "%b%s%b\n" "$text" "$text" "\033[0;10m"
    done
}

main() {
    if [[ -z $1 ]]; then
        ansicolor_table 38 0
    else
        local color_mode
        local color_type
        color_type=38
        color_mode=
        while [[ $# -gt 0 ]] ; do
            case "$1" in
                -b) color_type=48; shift ;;
                -t)
                    shift
                    if [[ "$1" =~ ^[0-9]+$ ]] && (( $1 >= 0 && $1 <= 10 )); then
                        color_mode="$1"
                        shift
                    else
                        wrong_args "-t" "$color_mode"
                    fi
                ;;
                -h|--help) usage ;;
                *) break ;;
            esac
        done
        if [[ -z $1 ]]; then
            ansicolor_table "$color_type" "$color_mode"
        elif [[ $# -gt 1 ]]; then
            echo  "Too many arguments, type ansicolor -h for usage." 1>&2
            exit -1
        elif [[ "$1" =~ ^[0-9]+$ ]] && (( $1 >= 0 && $1 <= 255 )); then
            ansicolor_list "$color_type" "$1" "$color_mode"
        else
            wrong_args "color code" "$1"
        fi
    fi
}

main "$@"

